package service

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/model"
)

const (
	asyncMediaRequestsDir  = "requests"
	asyncMediaResponsesDir = "responses"
	// A stored response is delivered to the job's owner on every query until it
	// expires; the cap bounds one accepted request's response payload.
	asyncMediaMaxResponseBytes = 32 << 20
	// Jobs executed per scheduler run. Claimed jobs are processed sequentially so
	// one run never opens more upstream calls than it can wait for.
	asyncMediaJobBatchSize = 5
	// The replayed request may poll an asynchronous vendor inside its own client
	// call, so the client timeout stays above the protocol observation timeout.
	asyncMediaReplayTimeoutSlackSeconds = 120
)

// AsyncMediaSummary is the system task result of one async media scheduler run.
type AsyncMediaSummary struct {
	Claimed    int `json:"claimed"`
	Succeeded  int `json:"succeeded"`
	Failed     int `json:"failed"`
	Recovered  int `json:"recovered"`
	FilesPurge int `json:"files_purged"`
}

func asyncMediaDir(name string) (string, error) {
	root := strings.TrimSpace(constant.AsyncMediaDir)
	if root == "" {
		return "", errors.New("async media storage directory is not configured")
	}
	path := filepath.Join(root, name)
	if err := os.MkdirAll(path, 0o755); err != nil {
		return "", err
	}
	return path, nil
}

// SaveAsyncMediaRequest stores the accepted request body. The job id is
// generated by the host, so the file name never carries caller input.
func SaveAsyncMediaRequest(jobID string, content io.Reader, maxBytes int64) (string, int64, error) {
	if strings.TrimSpace(jobID) == "" {
		return "", 0, errors.New("async media job id is required")
	}
	dir, err := asyncMediaDir(asyncMediaRequestsDir)
	if err != nil {
		return "", 0, err
	}
	path := filepath.Join(dir, jobID+".request")
	file, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return "", 0, err
	}
	written, copyErr := io.Copy(file, io.LimitReader(content, maxBytes+1))
	closeErr := file.Close()
	if copyErr != nil {
		_ = os.Remove(path)
		return "", 0, copyErr
	}
	if closeErr != nil {
		_ = os.Remove(path)
		return "", 0, closeErr
	}
	if maxBytes > 0 && written > maxBytes {
		_ = os.Remove(path)
		return "", 0, fmt.Errorf("request body exceeds %d bytes", maxBytes)
	}
	return path, written, nil
}

// SaveAsyncMediaResponse stores the replayed response body for later delivery.
func SaveAsyncMediaResponse(jobID string, content []byte) (string, error) {
	if strings.TrimSpace(jobID) == "" {
		return "", errors.New("async media job id is required")
	}
	dir, err := asyncMediaDir(asyncMediaResponsesDir)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, jobID+".response")
	if err := os.WriteFile(path, content, 0o600); err != nil {
		return "", err
	}
	return path, nil
}

// ReadAsyncMediaResponse returns the stored response body of one job.
func ReadAsyncMediaResponse(job *model.AsyncMediaJob) ([]byte, error) {
	if job == nil || strings.TrimSpace(job.ResponseFile) == "" {
		return nil, errors.New("stored response is gone")
	}
	path, err := resolveAsyncMediaFile(job.ResponseFile)
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path)
}

// ReadAsyncMediaRequest returns the accepted request body of one job.
func ReadAsyncMediaRequest(job *model.AsyncMediaJob) ([]byte, error) {
	if job == nil || strings.TrimSpace(job.RequestFile) == "" {
		return nil, errors.New("stored request is gone")
	}
	path, err := resolveAsyncMediaFile(job.RequestFile)
	if err != nil {
		return nil, err
	}
	return os.ReadFile(path)
}

// DeleteAsyncMediaFile removes one stored file. The configured directory is the
// only place job files are read from or written to.
func DeleteAsyncMediaFile(path string) {
	resolved, err := resolveAsyncMediaFile(path)
	if err != nil {
		return
	}
	if removeErr := os.Remove(resolved); removeErr != nil && !os.IsNotExist(removeErr) {
		common.SysError("remove async media file failed: " + removeErr.Error())
	}
}

// resolveAsyncMediaFile rejects paths outside the configured storage directory so
// a tampered row cannot read or delete arbitrary files.
func resolveAsyncMediaFile(path string) (string, error) {
	root := strings.TrimSpace(constant.AsyncMediaDir)
	if root == "" {
		return "", errors.New("async media storage directory is not configured")
	}
	absoluteRoot, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	absolutePath, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	if absolutePath != absoluteRoot && !strings.HasPrefix(absolutePath, absoluteRoot+string(os.PathSeparator)) {
		return "", errors.New("async media path escapes the storage directory")
	}
	return absolutePath, nil
}

// AsyncMediaStorageReady reports whether explicit asynchronous requests are
// accepted at all.
func AsyncMediaStorageReady() bool {
	return constant.AsyncMediaEnabled && strings.TrimSpace(constant.AsyncMediaDir) != ""
}

// RunAsyncMediaJobsOnce recovers interrupted jobs, executes claimed jobs and
// purges stored files past their retention deadline. It is the scheduled entry
// point of the explicit asynchronous media queue.
func RunAsyncMediaJobsOnce(ctx context.Context) AsyncMediaSummary {
	summary := AsyncMediaSummary{}
	now := common.GetTimestamp()
	staleBefore := now - int64(constant.AsyncMediaStaleMinutes)*60
	if constant.AsyncMediaStaleMinutes > 0 {
		summary.Recovered = int(model.RecoverStaleAsyncMediaJobs(staleBefore, now, model.AsyncMediaJobExpiry(now, constant.AsyncMediaRetentionHours)))
	}
	if !AsyncMediaStorageReady() {
		return summary
	}
	workers := constant.AsyncMediaWorkers
	if workers <= 0 {
		workers = 1
	}
	if workers > asyncMediaJobBatchSize {
		workers = asyncMediaJobBatchSize
	}
	claimed := model.ClaimQueuedAsyncMediaJobs(now, workers)
	summary.Claimed = len(claimed)
	for _, job := range claimed {
		if ctx.Err() != nil {
			return summary
		}
		if err := executeAsyncMediaJob(ctx, job); err != nil {
			logger.LogWarn(ctx, fmt.Sprintf("async media job %s failed: %s", job.JobID, err.Error()))
			summary.Failed++
			continue
		}
		summary.Succeeded++
	}
	summary.FilesPurge = purgeExpiredAsyncMediaFiles(now)
	return summary
}

// executeAsyncMediaJob replays one accepted request through the gateway's own
// image endpoint. The replay is an ordinary client request: channel selection,
// retries, task affinity, quota pre-consume, settlement, refunds and consume
// logs all keep running inside the official relay path.
//
// The job is never replayed a second time. After the request leaves this
// process the upstream call may already have started, and a retry could
// generate and bill twice; a transport failure therefore becomes a
// reconciliation record instead.
func executeAsyncMediaJob(ctx context.Context, job *model.AsyncMediaJob) error {
	now := common.GetTimestamp()
	body, err := ReadAsyncMediaRequest(job)
	if err != nil {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingNotCharged, 0, "", nil, "", err.Error(), now)
	}
	token, tokenErr := model.GetTokenById(job.TokenId)
	if tokenErr != nil || token == nil {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingNotCharged, 0, "", nil, "", "the accepting token no longer exists", now)
	}
	if token.UserId != job.UserId {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingNotCharged, 0, "", nil, "", "the accepting token changed owner", now)
	}
	if token.Status != common.TokenStatusEnabled {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingNotCharged, 0, "", nil, "", "the accepting token is disabled", now)
	}

	replayURL := fmt.Sprintf("http://127.0.0.1:%d%s", *common.Port, job.RequestPath)
	if strings.TrimSpace(job.RawQuery) != "" {
		replayURL += "?" + job.RawQuery
	}
	timeout := time.Duration(constant.TaskPluginProtocolTimeoutSeconds+asyncMediaReplayTimeoutSlackSeconds) * time.Second
	replayContext, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	request, requestErr := http.NewRequestWithContext(replayContext, http.MethodPost, replayURL, bytes.NewReader(body))
	if requestErr != nil {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingNotCharged, 0, "", nil, "", requestErr.Error(), now)
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Authorization", "Bearer sk-"+token.Key)
	request.Header.Set("X-New-Api-Async-Media-Job", job.JobID)

	client := &http.Client{Timeout: timeout}
	response, doErr := client.Do(request)
	if doErr != nil {
		billing := model.AsyncMediaBillingReconciliationPending
		if isDialFailure(doErr) {
			billing = model.AsyncMediaBillingNotCharged
		}
		// The request body is kept for diagnosis when the upstream call may have
		// started; it is deleted with the rest of the job files on retention.
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, billing, 0, "", nil, "", doErr.Error(), now)
	}
	defer response.Body.Close()
	payload, readErr := io.ReadAll(io.LimitReader(response.Body, asyncMediaMaxResponseBytes+1))
	if readErr != nil {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingReconciliationPending, response.StatusCode, "", nil, "", readErr.Error(), now)
	}
	if int64(len(payload)) > asyncMediaMaxResponseBytes {
		// The upstream work already happened and was billed, so a result the host
		// refuses to store is a failure with an unknown charge, never a silent
		// success carrying a truncated payload.
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, model.AsyncMediaBillingReconciliationPending, response.StatusCode, "", nil, "", fmt.Sprintf("replayed response exceeds the stored result limit of %d bytes", asyncMediaMaxResponseBytes), now)
	}

	contentType := response.Header.Get("Content-Type")
	originTaskID := strings.TrimSpace(response.Header.Get("X-New-Api-Task-Id"))
	if response.StatusCode >= 200 && response.StatusCode < 300 {
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusSucceeded, model.AsyncMediaBillingSettled, response.StatusCode, originTaskID, payload, contentType, "", now)
	}
	if response.StatusCode == http.StatusGatewayTimeout && originTaskID != "" {
		// The official task is durable and will be polled independently. Keep the
		// request for rendering its terminal result without submitting again.
		return finishAsyncMediaJob(job, model.AsyncMediaJobStatusAwaitingTask, model.AsyncMediaBillingReconciliationPending, response.StatusCode, originTaskID, nil, "", "", now)
	}
	billing := model.AsyncMediaBillingNotCharged
	if response.StatusCode >= 500 {
		// An observation timeout leaves a durable task that settles later, and a
		// gateway error may hide a started upstream call.
		billing = model.AsyncMediaBillingReconciliationPending
	}
	message := strings.TrimSpace(string(payload))
	if message == "" {
		message = fmt.Sprintf("replayed request answered HTTP %d", response.StatusCode)
	}
	return finishAsyncMediaJob(job, model.AsyncMediaJobStatusFailed, billing, response.StatusCode, originTaskID, payload, contentType, message, now)
}

// finishAsyncMediaJob records the terminal state, drops the accepted request file
// and keeps the stored response until its retention deadline.
func finishAsyncMediaJob(job *model.AsyncMediaJob, status model.AsyncMediaJobStatus, billingStatus string, httpStatus int, originTaskID string, payload []byte, contentType, message string, now int64) error {
	responsePath := ""
	if status == model.AsyncMediaJobStatusSucceeded {
		stored, err := SaveAsyncMediaResponse(job.JobID, payload)
		if err != nil {
			return err
		}
		responsePath = stored
	}
	expiresAt := model.AsyncMediaJobExpiry(now, constant.AsyncMediaRetentionHours)
	if status == model.AsyncMediaJobStatusAwaitingTask {
		return model.CompleteAsyncMediaJob(job, status, billingStatus, httpStatus, originTaskID, "", "", "", 0, expiresAt)
	}
	if err := model.CompleteAsyncMediaJob(job, status, billingStatus, httpStatus, originTaskID, responsePath, contentType, message, now, expiresAt); err != nil {
		return err
	}
	DeleteAsyncMediaFile(job.RequestFile)
	_ = model.ClearAsyncMediaJobRequestFile(job.JobID, now)
	return nil
}

// purgeExpiredAsyncMediaFiles removes stored files past their retention
// deadline. The job row stays as an audit record of the accepted request.
func purgeExpiredAsyncMediaFiles(now int64) int {
	if err := model.ExpireAwaitingAsyncMediaJobs(now); err != nil {
		common.SysError("expire waiting async media jobs failed: " + err.Error())
	}
	jobs := model.ListExpiredAsyncMediaJobs(now, 200)
	purged := 0
	for _, job := range jobs {
		DeleteAsyncMediaFile(job.RequestFile)
		DeleteAsyncMediaFile(job.ResponseFile)
		if err := model.ClearAsyncMediaJobFiles(job.JobID, now); err != nil {
			common.SysError("clear expired async media files failed: " + err.Error())
			continue
		}
		purged++
	}
	return purged
}

// isDialFailure reports whether the replay never reached the gateway, which
// means no upstream call can have started.
func isDialFailure(err error) bool {
	var opError *net.OpError
	if errors.As(err, &opError) {
		return opError.Op == "dial"
	}
	return errors.Is(err, net.ErrClosed)
}
